---
openapi: 3.0.3
info:
  title: Virtualize API
  description: |
    \"Moving`\" data access, Virtualizes data access to underlying persistence engines.
  version: 0.9.0
servers:
  - url: http://data-virt.provoly:8080
    description: Auto generated value
paths:
  /about/version:
    get:
      summary: Return current version of data virt
      tags:
        - Version Controller
      operationId: com.provoly.version.VersionController_getVersion
  /data-sources/id/{dataSourceId}:
    get:
      summary: Proxy for getting dataset, dataset version or a named query from its id.
      tags:
        - Data Source Controller
      operationId: com.provoly.virt.datasource.DataSourceController_getDataSourceDetail
      security:
        - oidc:
            - search
            - datasource_read
  /data-sources/id/{dataSourceId}/items:
    get:
      summary: Proxy for getting items from dataset, dataset version or named query.
      description: |
        Get 200 items from data source.
        It's possible to filter, and set more than one filter in query parameters.
      tags:
        - Data Source Controller
      operationId: com.provoly.virt.datasource.DataSourceController_getItems
      security:
        - oidc:
            - search
            - datasource_read
    post:
      summary: Proxy for getting items from dataset, dataset version or named query.
      description: |
        Get 200 items from data source.
        
        It is possible to search on one or more classes.
        On Mono class search, it returns items from all active datasets. It's possible to specify
        dataset versions ids. 200 items are returned. This limit can be adjusted,
        but cannot exceed 1000. Items can be sorted. Works only with a Mono Class search. If a sort is
        set, then the next page of results can be retrieved by specifying the \"searchAfter\" 
        value of the first search result.
        This property has a ttl: once the time has elapsed, you'll have to restart the search from the beginning.
        It's also possible to add one or more filters in query parameters and sort your results.
      tags:
        - Data Source Controller
      operationId: com.provoly.virt.datasource.DataSourceController_getItemsSearch
      security:
        - oidc:
            - search
            - datasource_read
  /data-sources/id/{dataSourceId}/items/aggregate:
    get:
      summary: Get aggregated results from dataset, dataset version or named query.
      description: |
        Named query must reference a mono class request. Only aggregatedBy is required.
        The default operation is count.
      tags:
        - Data Source Controller
      operationId: com.provoly.virt.datasource.DataSourceController_getItemsAggregate
      security:
        - oidc:
            - search
            - datasource_read
  /data-sources/id/{dataSourceId}/items/paginate:
    get:
      summary: Get all items from dataset, dataset version or named query
      description: |
        This endpoint is not restricted by the limit of max item number in a result.
        It returns all items from a datasource using server sent event. An order is necessary.
      tags:
        - Data Source Controller
      operationId: com.provoly.virt.datasource.DataSourceController_getPaginateItems
      security:
        - oidc:
            - search
            - datasource_read
  /data-sources/values:
    post:
      summary: Get distinct values on attribute column where value match a requested value
      description: |
        This endpoint is used to retrieve a list of possible values for an attribute in a datasource.
        The datasource available for this endpoint are Dataset and DatasetVersion
      tags:
        - Data Source Controller
      operationId: com.provoly.virt.datasource.DataSourceController_searchForAttributeValues
      security:
        - oidc:
            - datasource_read
  /datasets/id/{datasetId}/dataset-versions/id/{id}:
    post:
      tags:
        - Dataset Controller
      summary: Trigger asynchronous items insertion
      description: Import data by adding ItemDto list directly in a new version of a closed dataset
      operationId: com.provoly.virt.dataset.DatasetController_importData
      security:
        - oidc:
            - item_write
  /file:
    post:
      tags:
        - File Controller
      summary: Upload file
      description: Save file which will be linked to an item
      operationId: com.provoly.virt.file.FileController_receiveFile
      security:
        - oidc:
            - item_write
  /file/id/{id}:
    get:
      tags:
        - File Controller
      summary: Download file
      description: |
        Download file linked to an item by using the id generated during the upload.
        It's possible to retrieve part of the file by specifying the range in headers.
      operationId: com.provoly.virt.file.FileController_getFile
      security:
        - oidc:
            - search
            - dashboard_read
            - dataset_read
            - widget_catalog_read
  /file/icons:
    post:
      tags:
        - File Controller
      summary: Upload icon or illustration
      description: |
        Service used for saving an icon for oClass customization or
        an illustration for widget and dashboard.
      operationId: com.provoly.virt.file.FileController_receiveIcon
      security:
        - oidc:
            - class_write
            - dashboard_write
            - dataset_write
            - widget_catalog_write
    get:
      tags:
        - File Controller
      summary: Get all icons and illustrations names
      description: |
        Return the name of all uploaded icons and illustrations, with their corresponding type.
        It's possible to filter on type to get all icons or all illustrations.
      operationId: com.provoly.virt.file.FileController_getIconList
      security:
        - oidc:
            - class_read
            - search
            - dashboard_read
            - dataset_read
            - widget_catalog_read
  /file/icons/{name}:
    get:
      tags:
        - File Controller
      summary: Download icon or illustration
      description: Download the icon or illustration by using the id generated during the upload
      operationId: com.provoly.virt.file.FileController_getIcon
      security:
        - oidc:
            - class_read
            - search
            - dashboard_read
            - dataset_read
            - widget_catalog_read
    delete:
      tags:
        - File Controller
      summary: Delete icon or illustration
      description: This endpoint is only used for cleaning s3 server.
      operationId: com.provoly.virt.file.FileController_deleteIcon
      security:
        - oidc:
            - class_write
            - search
            - dashboard_write
            - dataset_write
            - widget_catalog_write
  /file/icons/{id}/{type}:
    put:
      tags:
        - File Controller
      summary: Set type to an icon or illustration
      description: |
        Type is necessary when uploading an icon or illustration,
        but it's possible to add a additional types with this endpoint.
      operationId: com.provoly.virt.file.FileController_setIconType
      security:
        - oidc:
            - class_write
            - search
            - dashboard_write
            - dataset_write
            - widget_catalog_write
  /imports/dataset/id/{datasetId}:
    post:
      tags:
        - Imports Controller
      summary: Asynchronous data import
      description: |
        Asynchronous data import that support csv file and zipped shapefile. It returns the
        created dataset version for dataset.
        NormalizeGeo is used to specify whether a shapefile should be normalized. For example, if a shapefile contains a polygon and a multi-polygon, set this property to true.
        ChunkSize is used to specify the number of items per chunk that data-virt will hold in memory during import.
      operationId: com.provoly.virt.importFile.ImportsController_importNewDataset
      security:
        - oidc:
            - item_write
  /items:
    post:
      tags:
        - Items Controller
      summary: Synchronous insertion of ItemDto collection
      description: Add items in the dataset version of a modifiable dataset.
      operationId: com.provoly.virt.item.ItemsController_insert
      security:
        - oidc:
            - item_write
  /items/id/{id}:
    get:
      tags:
        - Items Controller
      summary: Return item
      operationId: com.provoly.virt.item.ItemsController_get
      security:
        - oidc:
            - search
            - datasource_read
  /items/id/{id}/relations:
    get:
      tags:
        - Items Controller
      summary: Return all items related to the requested item
      operationId: com.provoly.virt.item.ItemsController_searchWithRelations
      security:
        - oidc:
            - search
            - datasource_read
  /items/id/{itemId}/attributes/name/{attributeName}/metadata/name/{metadataName}/{value}:
    post:
      tags:
        - Metadata Controller
      summary: Add metadata on specific attribute on specific item
      operationId: com.provoly.virt.metadata.MetadataController_setMetadataToAttribute
      security:
        - oidc:
            - item_write
  /items/id/{itemId}/metadata/name/{metadataName}/{value}:
    post:
      tags:
        - Metadata Controller
      summary: Add metadata on specific item
      operationId: com.provoly.virt.metadata.MetadataController_setMetadataToItem
      security:
        - oidc:
            - item_write
  /items/search:
    post:
      tags:
        - Search Controller
      summary: Get n items that match search criteria
      description: |
        It is possible to search on one or more classes.
        On Mono class search, it returns items from all active datasets. It's possible to specify
        dataset versions ids. 200 items are returned. This limit can be adjusted,
        but cannot exceed 1000. Items can be sorted. Works only with a Mono Class search. If a sort is
        set, then the next page of results can be retrieved by specifying the \"searchAfter\" 
        value of the first search result. 
        This property has a ttl: once the time has elapsed, you'll have to restart the search from the beginning.
      operationId: com.provoly.virt.search.SearchController_search
      security:
        - oidc:
            - search
  /items/search/named/{nameQueryId}:
    get:
      tags:
        - Search Controller
      summary: Returns items that match named query
      description: |
        Search criteria are stored in a named query. 
        It's possible to add a limit and a order like the classic search.
      operationId: com.provoly.virt.search.SearchController_searchByNamedQuery
      security:
        - oidc:
            - search
  /relations:
    post:
      tags:
        - Relations Controller
      summary: Save a list of relations
      description: |
        Registers a relation between two attributes of different oClasses 
        to link items of these oClasses. It creates a new item in the `relation` index in elasticsearch.
        The relationType must first be registered in `data-ref` service.
      operationId: com.provoly.virt.relation.RelationsController_saveRelations
      security:
        - oidc:
            - item_write
    delete:
      tags:
        - Relations Controller
      summary: Delete relation between two attributes
      description: Deleting a relation implies the dissociation between items linked by the relation.
      operationId: com.provoly.virt.relation.RelationsController_delete
      security:
        - oidc:
            - item_write
  /relations/aggregate:
    post:
      tags:
        - Relation Aggregate Controller
      summary: Update relations between items. Called by `data-link`
      description: |
        Data Link automatically analyze which relation is deprecated, 
        and update them by calling this endpoint with the `aggregateId` and the `link` which is the
         id of the attribute on which to delete and remake the relation.
      operationId: com.provoly.virt.relation.RelationAggregateController_updateAggregate
      security:
        - oidc:
            - update_relation_aggregate
components:
  securitySchemes:
    oidc:
      type: openIdConnect
      description: Authentication
      openIdConnectUrl: /auth/realms/provoly/.well-known/openid-configuration