
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provoly-exec-engine
  labels:
    app.kubernetes.io/component: provoly-exec-engine
    app.kubernetes.io/part-of: provoly

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: provoly-exec-engine
  labels:
    app.kubernetes.io/component: provoly-exec-engine
    app.kubernetes.io/part-of: provoly
data:
  application.yaml: |
    quarkus:    
      banner:
        enabled: false
      log:
        console:
          json: false
          level: TRACE
          format: "%d{HH:mm:ss} %-5p traceId=%X{traceId} parentId=%X{parentId} spanId=%X{spanId} [%c{2.}] (%t) %s%e%n"
    
      datasource:
        jdbc:
          url: jdbc:postgresql://provoly-postgresql:5432/provoly
        username: ${ref.database.user}
        password: ${ref.database.password}
          
    
      oidc:
        auth-server-url: https://sso.test.provoly.net/auth/realms/provoly
      oidc-client:
        auth-server-url: https://sso.test.provoly.net/auth/realms/provoly
        client-id: provoly
        credentials:
          secret: secret
        grant:
          type: password
        grant-options:
          password:
            username: ${provoly.exec.user}
            password: ${provoly.exec.password}
    
      rest-client:
        "data-virt":
          url: http://data-virt:8080
        

      otel:
        exporter:
          resource-attributes: env=dev-local
          otlp:
            traces:
              legacy-endpoint: http://localhost:4317
    provoly:
      exec:
        user: provoly_sync
        password: password
      application:
        version: test
        chart:
          version: test
    
    kafka:
      bootstrap:
        servers: kafka-provoly-kafka-bootstrap:9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: provoly-exec-engine
  labels:
    app.kubernetes.io/component: provoly-exec-engine
    app.kubernetes.io/part-of: provoly
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: provoly-exec-engine
      app.kubernetes.io/part-of: provoly
  template:
    metadata:
      labels:
        app.kubernetes.io/component: provoly-exec-engine
        app.kubernetes.io/part-of: provoly
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: provoly-exec-engine
      containers:
        - name: provoly-exec-engine
          image: dh2wltsh.gra7.container-registry.ovh.net/provoly/provoly-exec-engine:0.3.0
          imagePullPolicy: Always
          env:
            - name: REF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: provoly-postgresql
                  key: username
            - name: REF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: provoly-postgresql
                  key: password
          ports:
            - containerPort: 8080
              name: http

---

apiVersion: v1
kind: Service
metadata:
  name: provoly-exec-engine
  labels:
    app.kubernetes.io/component: provoly-exec-engine
    app.kubernetes.io/part-of: provoly
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/component: provoly-exec-engine
    app.kubernetes.io/part-of: provoly


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: provoly-exec-api
  labels:
    app.kubernetes.io/part-of: provoly
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - provoly.provoly-test.pangee.ovh
      secretName: provoly-test-ingress-tls
  rules:
      - host: provoly.provoly-test.pangee.ovh
        http:
          paths:
            - path: /api/exec(/|$)(.*)
              pathType: Prefix
              backend:
                service:
                  name: provoly-exec-engine
                  port:
                    name: http
