openapi: 3.0.3
info:
  title: API Baseline
  description: CRUD Operation on repositories data
  version: 0.7.0
servers:
  - url: http://data-ref.provoly.com
paths:
  /about/version:
    get:
      tags:
        - Version Controller
      summary: Retrieve the application and chart versions
      operationId: com.provoly.version.VersionController_getVersion
  /model/categories:
    put:
      tags:
        - Model Controller
      summary: Save a new category
      description: |
        They are used to categorise attributes of a data model. 
        If a category with this id already exists, update it.
      operationId: com.provoly.ref.model.ModelController_addCategory
      security:
        - oidc:
            - class_write
    get:
      tags:
        - Model Controller
      summary: Retrieve all categories
      operationId: com.provoly.ref.model.ModelController_getCategories
      security:
        - oidc:
            - class_read
            - search
            - datasource_read
  /model/categories/{id}:
    get:
      tags:
        - Model Controller
      summary: Retrieve a category based on its identifier
      operationId: com.provoly.ref.model.ModelController_getCategory
      security:
        - oidc:
            - class_read
    delete:
      tags:
        - Model Controller
      summary: Delete a category based on its identifier
      operationId: com.provoly.ref.model.ModelController_deleteCategory
      security:
        - oidc:
            - class_write
  /model/field:
    post:
      tags:
        - Model Controller
      summary: Save a new field
      description: |
        A field is required for defining an attribute in an oClass. 
        It can be used several times in the same oClass, or in different oClasses.
      operationId: com.provoly.ref.model.ModelController_addField
      security:
        - oidc:
            - field_write
  /model/fields:
    post:
      tags:
        - Model Controller
      summary: Save a new collection of fields
      operationId: com.provoly.ref.model.ModelController_addFields
      security:
        - oidc:
            - field_write
    get:
      tags:
        - Model Controller
      summary: Retrieve all existing fields
      operationId: com.provoly.ref.model.ModelController_getFields
      security:
        - oidc:
            - field_read
            - search
            - datasource_read
  /model/fields/{id}:
    get:
      tags:
        - Model Controller
      summary: Retrieve a field based on its identifier
      operationId: com.provoly.ref.model.ModelController_getFieldById
      security:
        - oidc:
            - field_read
            - item_write
    delete:
      tags:
        - Model Controller
      summary: Delete a field based on its identifier
      description: Deleting a field is only possible if it's not used in a oclass or named query.
      operationId: com.provoly.ref.model.ModelController_deleteFieldById
      security:
        - oidc:
            - field_read
            - item_write
            - search
            - datasource_read
  /model/fields/{id}/associations:
    get:
      tags:
        - Model Controller
      summary: Retrieve all field's associate items
      description: A field can be used in oClasses and named queries.
      operationId: com.provoly.ref.model.ModelController_getAssociationOfField
      security:
        - oidc:
            - field_read
            - field_write
  /model/fields/class/{id}:
    get:
      tags:
        - Model Controller
      summary: Retrieve all existing fields for an oClass
      operationId: com.provoly.ref.model.ModelController_getFieldsForClass
      security:
        - oidc:
            - field_read
            - search
            - item_write
            - datasource_read
  /model/class:
    post:
      tags:
        - Model Controller
      summary: Save or update new oClass
      description: |
        An oClass is made up of attributes and is used to define the data model that will be inserted. 
        An attribute belongs to a single class, and can be grouped by category. OClass names must be unique 
        and attributes ids must be unique.
        If class with same id already exists, update it.
        Note: It's not possible to change fields.
      operationId: com.provoly.ref.model.ModelController_saveClass
      security:
        - oidc:
            - class_write
    get:
      tags:
        - Model Controller
      summary: Retrieve all defined oClasses
      operationId: com.provoly.ref.model.ModelController_get
      security:
        - oidc:
            - class_read
            - search
            - datasource_read
  /model/class/id/{id}:
    get:
      tags:
        - Model Controller
      summary: Retrieve an oClass based on its identifier
      operationId: com.provoly.ref.model.ModelController_getById
      security:
        - oidc:
            - class_read
            - search
            - datasource_read
    delete:
      tags:
        - Model Controller
      summary: Delete an oClass based on its identifier
      description: |
        Delete a class is possible if not used elsewhere. Deleting a class means deleting the table that
        contained the data
      operationId: com.provoly.ref.model.ModelController_deleteClass
      security:
        - oidc:
            - class_write
  /model/class/id/{id}/details:
    get:
      tags:
        - Model Controller
      summary: Retrieve an oClass based on its identifier with more details
      description: |
        This oClass contains more information about the attributes used in the oClass,
        with details of the associated fields.
      operationId: com.provoly.ref.model.ModelController_getDetails
      security:
        - oidc:
            - class_read
            - search
            - datasource_read
  /model/class/id/{id}/attribute:
    put:
      tags:
        - Model Controller
      summary: Save a new attribute to a class
      operationId: com.provoly.ref.model.ModelController_addAttribute
      security:
        - oidc:
            - class_write
  /model/class/id/{classId}/attribute/id/{attributeId}:
    delete:
      tags:
        - Model Controller
      summary: Delete an attribute based on its identifier
      operationId: com.provoly.ref.model.ModelController_deleteAttribute
      security:
        - oidc:
            - class_write
  /model/class/datasets/count:
    get:
      tags:
        - Model Controller
      operationId: com.provoly.ref.model.ModelController_getDatasetCountByClass
      security:
        - oidc:
            - class_read
  /model/class/field/{id}:
    get:
      tags:
        - Model Controller
      summary: Retrieve all classes based on the identifier of a field
      operationId: com.provoly.ref.model.ModelController_getByField
      security:
        - oidc:
            - class_read
  /model/class/{id}/associations:
    get:
      tags:
        - Model Controller
      summary: Retrieve all usages of a class
      operationId: com.provoly.ref.model.ModelController_getClassAssociations
      security:
        - oidc:
            - class_read
  /model/id/{classId}/metadata/id/{metadataDefId}:
    put:
      tags:
        - Model Controller
      operationId: com.provoly.ref.dataset.ModelController_setMetadataToClass
      summary: Add metadata to a class
      security:
        - oidc:
            - class_write
    delete:
      tags:
        - Model Controller
      operationId: com.provoly.ref.dataset.ModelController_deleteMetadataToClass
      summary: Delete metadata of a class
      security:
        - oidc:
            - class_write
  /model/attribute/{id}/associations:
    get:
      tags:
        - Model Controller
      summary: Retrieve all usages of an attribute
      operationId: com.provoly.ref.model.ModelController_getAttributeAssociations
      security:
        - oidc:
            - class_read
  /model/storages:
    get:
      tags:
        - Model Controller
      summary: Retrieve available storages
      description: Retrieve the list of available storages
      operationId: com.provoly.ref.model.ModelController_getStorages
      security:
        - oidc:
            - class_write
  /customclass/all/param:
    get:
      tags:
        - Custom Class Controller
      summary: Retrieve all custom classes
      operationId: com.provoly.ref.customclass.CustomClassController_getAll
      security:
        - oidc:
            - class_read
            - search
            - datasource_read
  /customclass/all/param/{domain}:
    get:
      tags:
        - Custom Class Controller
      summary: Retrieve the list of custom classes for a domain
      operationId: com.provoly.ref.customclass.CustomClassController_getByDomain
      security:
        - oidc:
            - class_read
  /customclass/id/{id}/param/{domain}:
    put:
      tags:
        - Custom Class Controller
      summary: Save a new custom class by adding its configuration JSON file
      operationId: com.provoly.ref.customclass.CustomClassController_addCustomClass
      security:
        - oidc:
            - class_write
    get:
      tags:
        - Custom Class Controller
      summary: Retrieve a JSON file describing a custom class based on its identifier and its domain
      operationId: com.provoly.ref.customclass.CustomClassController_getCustomClass
      security:
        - oidc:
            - class_read
  /datasets:
    post:
      tags:
        - Dataset Controller
      summary: Save a new dataset for a specific oClass
      description: |
        A dataset is a coherent, versioned (functionally) set of data belonging to the same class.
        Dataset could be CLOSED and will therefore have several versions, OPEN or MODIFIABLE.
      operationId: com.provoly.ref.dataset.DatasetController_addDataset
      security:
        - oidc:
            - dataset_write
    put:
      tags:
        - Dataset Controller
      summary: Update a dataset based on its identifier
      description: You can only update the dataset name, description, metadata and groups, you cannot change its id, type or OClass.
      operationId: com.provoly.ref.dataset.DatasetController_update
      security:
        - oidc:
            - dataset_write
    get:
      tags:
        - Dataset Controller
      summary: Get all datasets
      operationId: com.provoly.ref.dataset.DatasetController_getAll
      security:
        - oidc:
            - dataset_read
  /datasets/id/{id}:
    get:
      tags:
        - Dataset Controller
      operationId: com.provoly.ref.dataset.DatasetController_get
      summary: Retrieve a dataset based on its identifier.
      description: Also returns the metadata attached to the dataset, if any.
      security:
        - oidc:
            - dataset_read
            - search
    delete:
      tags:
        - Dataset Controller
      summary: Delete a dataset based on its identifier
      description: Deleting a dataset is not possible if dataset-version are associated with it
      operationId: com.provoly.ref.dataset.DatasetController_delete
      security:
        - oidc:
            - dataset_write
  /datasets/id/{id}/dataset-version:
    get:
      tags:
        - Dataset Controller
      summary: Retrieve the last active dataset version based on its dataset id
      operationId: com.provoly.ref.dataset.DatasetController_getDatasetVersionByDatasetId
      security:
        - oidc:
            - dataset_read
  /datasets/id/{id}/dataset-versions:
    get:
      tags:
        - Dataset Controller
      summary: Retrieve all dataset versions by the identifier of its dataset
      operationId: com.provoly.ref.dataset.DatasetController_getAllById
      security:
        - oidc:
            - search
            - dataset_read
            - datasource_read
  /datasets/{id}/associations:
    get:
      tags:
        - Dataset Controller
      summary: Retrieve all usages of a dataset
      operationId: com.provoly.ref.dataset.DatasetController_getAssociationsByDatasetId
      security:
        - oidc:
            - dataset_read
  /datasets/id/{datasetId}/metadata/id/{metadataDefId}:
    put:
      tags:
        - Dataset Controller
      operationId: com.provoly.ref.dataset.DatasetController_setMetadata
      summary: Add metadata to a dataset
      security:
        - oidc:
            - dataset_write
    delete:
      tags:
        - Dataset Controller
      operationId: com.provoly.ref.dataset.DatasetController_deleteMetadata
      summary: Delete metadata of a dataset
      security:
        - oidc:
            - dataset_write
  /datasets/class/{id}:
    get:
      tags:
        - Dataset Controller
      summary: Retrieve all datasets associated to a class
      operationId: com.provoly.ref.dataset.DatasetController_getAllForClass
      security:
        - oidc:
            - class_read
            - search
  /datasets/name/{name}:
    get:
      tags:
        - Dataset Controller
      operationId: com.provoly.ref.dataset.DatasetController_getByName
      summary: Retrieve a dataset based on its name
      security:
        - oidc:
            - dataset_read
  /datasets/name/{datasetName}/dataset-version:
    get:
      tags:
        - Dataset Controller
      summary: Retrieve the last active dataset version of a dataset by its name
      operationId: com.provoly.ref.dataset.DatasetController_getDatasetVersionByDatasetName
      security:
        - oidc:
            - dataset_read
  /dataset-versions:
    post:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_create
      summary: Save a new dataset version
      security:
        - oidc:
            - item_write
    put:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_updateState
      summary: Update the state of a dataset version
      description: |
        A dataset version has multiple states to indicate the level of availability of the data imported.
        Each state can be modified to a specific set of other states. For example, if a dataset's state is `LOADING`,
        it can only obtain the `INDEXING` or `ERROR` states.
      security:
        - oidc:
            - item_write
    get:
      tags:
        - Dataset Version Controller
      summary: Retrieve all dataset versions
      description: |
        A dataset version is an instantiation of a dataset. It allows us to have coherent and versioned class data. 
        The parameter hasWarnings in the response body is a boolean used to indicate if dataset-version import's generated some warnings.
      operationId: com.provoly.ref.dataset.DatasetVersionController_getAll
      security:
        - oidc:
            - dataset_read
  /dataset-versions/id/{id}:
    get:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_get
      summary: Retrieve a dataset version based on its identifier. It also returns its associated metadata.
      security:
        - oidc:
            - dataset_read
            - search
    delete:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_delete
      summary: Delete a dataset version based on its identifier
      security:
        - oidc:
            - dataset_write
  /dataset-versions/id/{datasetVersionId}/metadata/id/{metadataDefId}:
    put:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_setMetadata
      summary: Add metadata to a dataset version
      security:
        - oidc:
            - dataset_write
    delete:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_deleteMetadata
      summary: Delete the metadata related to a dataset version
      security:
        - oidc:
            - dataset_write
  /dataset-versions/id/{id}/activate:
    post:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_activate
      summary: Activate a dataset version based on its identifier
      description: |
        It also deactivates the previous one. 
        It is only possible to have only one version of an active dataset.
      security:
        - oidc:
            - dataset_read
  /dataset-versions/id/{id}/deactivate:
    post:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_deactivate
      summary: Deactivate a dataset version based on its identifier
      security:
        - oidc:
            - dataset_read
  /dataset-versions/class/{classId}:
    get:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_getAllForClass
      summary: Retrieve all dataset versions related to the class contained in its dataset
      security:
        - oidc:
            - search
  /dataset-versions/id/{datasetVersionId}/previews:
    get:
      tags:
        - Dataset Version Controller
      operationId: com.provoly.ref.dataset.DatasetVersionController_getDatasetVersionPreviews
      summary: Returns the details of errors and warnings for a dataset version
      security:
        - oidc:
            - dataset_read
  /metadata:
    post:
      tags:
        - Metadata Def Controller
      operationId: com.provoly.ref.metadata.MetadataDefController_addMetadata
      summary: Save a new metadata definition
      description: |
        A metadata is used to add context to an entity. 
        Metadata definitions must first be created before being used on an entity.
      security:
        - oidc:
            - metadata_item_ref_write
    get:
      tags:
        - Metadata Def Controller
      summary: Retrieve all metadata definitions
      operationId: com.provoly.ref.metadata.MetadataDefController_getAll
      security:
        - oidc:
            - metadata_item_ref_read
            - item_write
            - dashboard_write
            - dataset_write
  /metadata/id/{metadataId}:
    get:
      tags:
        - Metadata Def Controller
      operationId: com.provoly.ref.metadata.MetadataDefController_getById
      summary: Retrieve a metadata definition based on its identifier
      security:
        - oidc:
            - metadata_item_ref_read
            - item_write
            - search
            - dashboard_read
  /metadata/name/{metadataName}:
    get:
      tags:
        - Metadata Def Controller
      operationId: com.provoly.ref.metadata.MetadataDefController_getByName
      summary: Retrieve a metadata based on its name
      security:
        - oidc:
            - metadata_item_ref_read
            - item_write
            - search
            - datasource_read
  /metadata/slug/{metadataSlug}:
    get:
      tags:
        - Metadata Def Controller
      operationId: com.provoly.ref.metadata.MetadataDefController_getBySlug
      summary: Retrieve a metadata based on its slug
      security:
        - oidc:
            - metadata_item_ref_read
            - item_write
            - search
            - datasource_read
  /predicates:
    post:
      tags:
        - Predicate Controller
      summary: Save a new predicate
      description: Predicates are used to define abac rules. They can refer to context variables.
      operationId: com.provoly.ref.abac.predicate.PredicateController_addPredicate
      security:
        - oidc:
            - data_access_write
    get:
      tags:
        - Predicate Controller
      summary: Retrieve all defined predicates
      operationId: com.provoly.ref.abac.predicate.PredicateController_getAllPredicates
      security:
        - oidc:
            - data_access_read
  /abac/context:
    get:
      tags:
        - Metadata Context Controller
      summary: Retrieve all defined context variables
      description: |
        Context variables are used in our predicates to give more context information. \
        We treat it as metadata, and it is notably used as a condition of an ABAC rule, or its expression for example.
      operationId: com.provoly.ref.abac.MetadataContextController_listContextVariables
      security:
        - oidc:
            - metadata_context_read
            - search
            - datasource_read
    put:
      tags:
        - Metadata Context Controller
      summary: Save a new context variable
      operationId: com.provoly.ref.abac.MetadataContextController_addContextVariable
      security:
        - oidc:
            - metadata_context_write
  /abac/context/{variableName}:
    get:
      tags:
        - Metadata Context Controller
      summary: Retrieve a context variable based on its name
      operationId: com.provoly.ref.abac.MetadataContextController_getContextVariable
      security:
        - oidc:
            - metadata_context_read
    delete:
      tags:
        - Metadata Context Controller
      summary: Delete a context variable based on its name
      operationId: com.provoly.ref.abac.MetadataContextController_deleteContextVariable
      security:
        - oidc:
            - metadata_context_write
  /abac/rules:
    get:
      tags:
        - Abac Controller
      summary: Retrieve all ABAC rules
      description: |
        The ABAC (Attribute-Based Access Control) are rules and predicates.
        They allow us to provide access to users based on who they are rather than what they do.
      operationId: com.provoly.ref.abac.AbacController_getRules
      security:
        - oidc:
            - data_access_read
    post:
      tags:
        - Abac Controller
      summary: Save a new ABAC rule
      operationId: com.provoly.ref.abac.AbacController_addRule
      security:
        - oidc:
            - data_access_write
  /abac/rules/class/{oClassId}:
    get:
      tags:
        - Abac Controller
      summary: Retrieve all ABAC rules for a class based on its identifier
      operationId: com.provoly.ref.abac.AbacController_getRulesFor
      security:
        - oidc:
            - data_access_read
            - search
            - datasource_read
  /abac/rules/id/{ruleId}:
    get:
      tags:
        - Abac Controller
      summary: Retrieve an ABAC rule based on its identifier
      operationId: com.provoly.ref.abac.AbacController_getRule
      security:
        - oidc:
            - data_access_read
  /abac/rules/{ruleId}:
    delete:
      tags:
        - Abac Controller
      summary: Delete an ABAC rule based on its identifier
      operationId: com.provoly.ref.abac.AbacController_deleteRule
      security:
        - oidc:
            - data_access_write
  /predicates/id/{id}:
    get:
      tags:
        - Predicate Controller
      summary: Retrieve a predicate based on its identifier
      operationId: com.provoly.ref.abac.predicate.PredicateController_getPredicate
      security:
        - oidc:
            - data_access_read
            - search
            - datasource_read
  /meta-provisioning:
    get:
      tags:
        - Meta Provisioning Controller
      summary: Retrieve the automatic metadata feeding rules for an item during its insertion
      operationId: com.provoly.ref.metaProvisioning.MetaProvisioningController_getAll
      security:
        - oidc:
            - metadata_item_ref_read
    post:
      tags:
        - Meta Provisioning Controller
      summary: Save a new an automatic metadata feeding rule
      operationId: com.provoly.ref.metaProvisioning.MetaProvisioningController_add
      security:
        - oidc:
            - metadata_item_ref_write
  /meta-provisioning/id/{id}:
    get:
      tags:
        - Meta Provisioning Controller
      summary: Retrieve an automatic metadata feeding rule based on its identifier
      operationId: com.provoly.ref.metaProvisioning.MetaProvisioningController_getById
      security:
        - oidc:
            - metadata_item_ref_read
    delete:
      tags:
        - Meta Provisioning Controller
      summary: Delete an automatic feeding rule based on its identifier
      operationId: com.provoly.ref.metaProvisioning.MetaProvisioningController_delete
      security:
        - oidc:
            - metadata_item_ref_write
  /relation-types:
    get:
      tags:
        - Relation Type Controller
      summary: Retrieve all relation types
      operationId: com.provoly.ref.relation.RelationTypeController_getAll
      security:
        - oidc:
            - class_read
            - search
            - datasource_read
    post:
      tags:
        - Relation Type Controller
      summary: Save a new relation type
      operationId: com.provoly.ref.relation.RelationTypeController_save
      security:
        - oidc:
            - class_write
  /relation-types/id/{id}:
    get:
      tags:
        - Relation Type Controller
      summary: Retrieve a relation type based on its identifier
      operationId: com.provoly.ref.relation.RelationTypeController_getById
      security:
        - oidc:
            - class_read
    delete:
      tags:
        - Relation Type Controller
      summary: Delete a relation type based on its identifier
      operationId: com.provoly.ref.relation.RelationTypeController_delete
      security:
        - oidc:
            - class_write
  /links:
    get:
      tags:
        - Link Controller
      summary: Retrieve all links
      description: |
        A link is a connections or relationships between attributes of classes. 
        They allow us to represent associations between our objects.
      operationId: com.provoly.ref.link.LinkController_getAll
      security:
        - oidc:
            - link_read
    post:
      tags:
        - Link Controller
      summary: Save a new link defining a relationship
      operationId: com.provoly.ref.link.LinkController_saveLink
      security:
        - oidc:
            - link_write
  /links/id/{id}:
    get:
      tags:
        - Link Controller
      summary: Retrieve a link based on its identifier
      operationId: com.provoly.ref.link.LinkController_getById
      security:
        - oidc:
            - link_read
            - update_relation_aggregate
    delete:
      tags:
        - Link Controller
      summary: delete a link based on its identifier
      operationId: com.provoly.ref.link.LinkController_deleteLink
      security:
        - oidc:
            - link_write
  /data-sources/id/{dataSourceId}:
    get:
      tags:
        - Data Source Controller
      summary: Retrieve a DataSource based on its identifier
      description: |
        DataSources are sources containing data that can be displayed in widgets. They include
        named queries, dataset versions and datasets.
      operationId: com.provoly.ref.datasource.DataSourceController_getDatasourceDetail
      security:
        - oidc:
            - search
            - datasource_read
  /users:
    get:
      tags:
        - User Controller
      operationId: com.provoly.ref.user.UserController_getAllUsers
      summary: Retrieve all users
      security:
        - oidc:
            - user_read
  /users/me:
    get:
      tags:
        - User Controller
      operationId: com.provoly.ref.user.UserController_getUserInfo
      summary: Retrieve the current user info
  /users/id/{userId}/metadata:
    get:
      tags:
        - User Controller
      operationId: com.provoly.ref.user.UserController_getProfileValuesByUserId
      summary: Retrieve all profile values of a user based on its identifier
      security:
        - oidc:
            - metadata_user_read
  /users/id/{userId}/metadata/id/{metadataDefId}:
    put:
      tags:
        - User Controller
      operationId: com.provoly.ref.user.UserController_addProfileForUser
      summary: Save new profile values for a user based on its identifier
      security:
        - oidc:
            - metadata_user_write
    delete:
      tags:
        - User Controller
      operationId: com.provoly.ref.user.UserController_deleteProfileForUser
      summary: Delete all profile values of a user based on its identifier
      security:
        - oidc:
            - metadata_user_write
  /users/me/metadata:
    get:
      tags:
        - User Controller
      operationId: com.provoly.ref.user.UserController_getMines
      security:
        - oidc:
            - metadata_user_ref_read
            - metadata_user_read
            - search
  /users/metadata:
    post:
      tags:
        - User Profile Controller
      operationId: com.provoly.ref.user.metadata.UserProfileController_addUserProfile
      summary: Save a new user profile
      security:
        - oidc:
            - metadata_user_ref_write
    get:
      tags:
        - User Profile Controller
      operationId: com.provoly.ref.user.metadata.UserProfileController_getAll
      summary: Retrieve all user profiles
      security:
        - oidc:
            - metadata_user_ref_read
  /users/metadata/{metadataId}:
    get:
      tags:
        - User Profile Controller
      operationId: com.provoly.ref.user.metadata.UserProfileController_getDefById
      summary: Retrieve a user profile based on its identifier
      security:
        - oidc:
            - metadata_user_ref_read
  /users/me/namedquery:
    post:
      tags:
        - Named Query Controller
      summary: Save a new named query
      operationId: com.provoly.ref.user.NamedQueryController_saveNamedQuery
      security:
        - oidc:
            - search
    get:
      tags:
        - Named Query Controller
      summary: Retrieve all named queries of the current user
      operationId: com.provoly.ref.user.NamedQueryController_getMines
      security:
        - oidc:
            - search
  /users/me/namedquery/{id}:
    get:
      tags:
        - Named Query Controller
      summary: Retrieve a named query based on its identifier
      description: |
        This endpoint is used only by data-virt and allows executing a private namedQuery\
        that we do not own if we know its ID.
      operationId: com.provoly.ref.user.NamedQueryController_getNamedQueryById
      security:
        - oidc:
            - search
            - data_virt
    delete:
      tags:
        - Named Query Controller
      summary: Delete a named query based on its identifier
      description: Currently, only private named queries can be deleted
      operationId: com.provoly.ref.user.NamedQueryController_deleteForMe
      security:
        - oidc:
            - search
  /users/me/namedquery/{id}/execution:
    post:
      tags:
        - Named Query Controller
      summary: Save the execution time of a named query based on its identifier
      operationId: com.provoly.ref.user.NamedQueryController_updateNamedQueryExecution
      security:
        - oidc:
            - search
  /users/me/namedquery/{id}/favorite:
    post:
      tags:
        - Named Query Controller
      summary: Set a named query as a favorite for the current user
      operationId: com.provoly.ref.user.NamedQueryController_addToMineFavorite
      security:
        - oidc:
            - search
    delete:
      tags:
        - Named Query Controller
      summary: Unset a named query as the favorite for the current user
      operationId: com.provoly.ref.user.NamedQueryController_removeFromMineFavorite
      security:
        - oidc:
            - search
  /users/me/namedquery/{id}/info:
    get:
      tags:
        - Named Query Controller
      summary: Retrieve all information of a named query based on its identifier
      operationId: com.provoly.ref.user.NamedQueryController_getUserNamedQueryById
      security:
        - oidc:
            - search
  /users/me/dashboards:
    post:
      tags:
        - Dashboard Controller
      summary: Save a new dashboard
      description: |
        Saves a dashboard for the current user. Groups can be added, otherwise the dashboard is private by default. If the group added is "ALL", then the dashboard can be consulted by anyone. If the group added is "AUTHENTICATED", then everyone will have the right to view the dashboard except the anonymous user.
        A list of missing groups is returned when the list of groups added to the dashboard does not match those present in the datasets, and the dashboard is not created.
      operationId: com.provoly.ref.dashboard.DashboardController_saveDashboard
      security:
        - oidc:
            - dashboard_write
    get:
      tags:
        - Dashboard Controller
      summary: Retrieve the dashboards of the current user
      operationId: com.provoly.ref.dashboard.DashboardController_getAllForCurrentUser
      security:
        - oidc:
            - dashboard_read
  /users/me/dashboards/id/{dashboardId}/metadata/id/{metadataDefId}:
    put:
      tags:
        - Dashboard Controller
      operationId: com.provoly.ref.dashboard.DashboardController_setMetadata
      summary: Save new metadata values for a dashboard based on its identifier
      security:
        - oidc:
            - dashboard_write
    delete:
      tags:
        - Dashboard Controller
      operationId: com.provoly.ref.dashboard.DashboardController_deleteMetadata
      summary: Delete metadata values for a dashboard based on its identifier
      security:
        - oidc:
            - dashboard_write
  /users/me/dashboards/id/{id}:
    get:
      tags:
        - Dashboard Controller
      summary: Retrieve a dashboard based on its identifier
      operationId: com.provoly.ref.dashboard.DashboardController_getById
      security:
        - oidc:
            - dashboard_read
    delete:
      tags:
        - Dashboard Controller
      summary: Delete a dashboard based on its identifier
      operationId: com.provoly.ref.dashboard.DashboardController_delete
      security:
        - oidc:
            - dashboard_write
  /users/me/dashboards/id/{id}/manifest:
    get:
      tags:
        - Dashboard Controller
      summary: Retrieve the manifest of the dashboard based on its identifier
      operationId: com.provoly.ref.dashboard.DashboardController_getDashBoardManifest
      security:
        - oidc:
            - dashboard_read
  /widget/catalog:
    post:
      tags:
        - Widget Controller
      summary: Adding a JSON file describing a widget configuration
      operationId: com.provoly.ref.widget.WidgetController_addWidget
      security:
        - oidc:
            - widget_catalog_write
    get:
      tags:
        - Widget Controller
      summary: Retrieve all saved widgets
      operationId: com.provoly.ref.widget.WidgetController_getAll
      security:
        - oidc:
            - widget_catalog_read
  /widget/catalog/id/{id}:
    get:
      tags:
        - Widget Controller
      summary: Retrieve a widget configuration based on its identifier
      operationId: com.provoly.ref.widget.WidgetController_getWidget
      security:
        - oidc:
            - widget_catalog_read
    delete:
      tags:
        - Widget Controller
      summary: Delete a widget configuration based on its identifier
      operationId: com.provoly.ref.widget.WidgetController_deleteWidget
      security:
        - oidc:
            - widget_catalog_write
  /types:
    get:
      tags:
        - Type Controller
      operationId: com.provoly.ref.model.TypeController_getAll
      summary: Retrieve all types
      security:
        - oidc:
            - class_read
  /groups:
    post:
      tags:
        - Group Controller
      operationId: com.provoly.ref.model.GroupController_saveGroup
      summary: Add new group
      security:
        - oidc:
            - dashboard_write
    get:
      tags:
        - Group Controller
      operationId: com.provoly.ref.model.GroupController_getAll
      summary: Retrieve all groups
      security:
        - oidc:
            - dashboard_read
  /notification:
    post:
      tags:
        - Notification Controller
      summary: Save a new notification to the associated users
      operationId: com.provoly.ref.message.notification.NotificationController_addNotification
      security:
        - oidc:
            - notification_write
  /notification/me:
    delete:
      tags:
        - Notification Controller
      summary: Delete all notifications related to the associated user
      operationId: com.provoly.ref.message.notification.NotificationController_acknowledgeAllNotification
  /notification/me/id/{id}:
    delete:
      tags:
        - Notification Controller
      summary: Remove a notification from its associated user
      operationId: com.provoly.ref.message.notification.NotificationController_acknowledgeNotification
components:
  securitySchemes:
    oidc:
      type: openIdConnect
      description: Authentication
      openIdConnectUrl: https://auth/realms/provoly/.well-known/openid-configuration