== How-tos

[.howtos]
--
* xref:howtos/runjiblocaly.adoc[Run jib locally]
* xref:howtos/run-an-application.adoc[Run an application]
* xref:howtos/reuse-containers.adoc[Reuse test containers]
* xref:howtos/run-data-ref-dependent-tests.adoc[Running tests depending on data-ref]
* xref:howtos/write-tests-with-kafka-companion.adoc[Write tests with kafka companion]
* xref:howtos/import.adoc[Import data with APIs]
* xref:howtos/tracing-locally-tests.adoc[Run traces locally with jaeger]
* xref:howtos/run-exec-engine-locally.adoc[Run exec-engine module locally]
* xref:howtos/insert-items-into-database.adoc[Insert (or update) items into database]
--

== Check list
--
* If your feature modifies the API. You have to mirror the impacts the `\{project_name}/src/main/resources/META-INF/openapi.yaml` file.
If your modification is breaking, the issue must be labeled as BREAKING CHANGE and the client must be informed of the changement. The linter will then be run again.
* If you're feature beaks API backward compatibility, ensure the ticket has the `breaking change` label
* If your feature impacts the database model, you changes must be placed under the `\{project_name}/src/main/resources/db/migration` folder.
* If your feature impacts database content, you need to test locally
* If you need to initialize a value in database depending on the environment, you need to put a migration script placed under the `\{project-name}/src/main/resources/db.onetime` folder.
* If your feature adds or removes user roles, you have to mirror those changes in the realm **json** file `provoly-common/src/main/resources/dev-realm.json` and in the impacted `\{project_name}/src/main/resources/META-INF/openapi.yaml` file.
* If you modify one of the openapi, check the redocly github build for warnings
--

Project_name could be :
--
- data-ref
- data-virt
- provoly-transfo-engine
- provoly-exec-engine
--