quarkus:
  management:
    enabled: true
    port: 8081
  oidc:
    client-id: provoly
  oidc-client:
    grant-options:
      password:
        username: ${provoly.sync.user}
        password: ${provoly.sync.password}
    auth-server-url: http://localhost:9080/realms/provoly

mp:
  messaging:
    incoming:
      item:
        pattern: true
        topic: "ds-.*"
        value:
          deserializer: io.quarkus.kafka.client.serialization.JsonObjectDeserializer
        commit-strategy: latest
        auto:
          offset:
            reset: earliest

      relation-aggregate:
        topic: relation-aggregate
        commit-strategy: latest
        max:
          poll:
            records: 100
        auto:
          offset:
            reset: earliest
        failure-strategy: dead-letter-queue
        dead-letter-queue:
          topic: dlq-relation-aggregate
          value:
            serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

"%dev":
  quarkus:
    management:
      port: 8092
    oidc:
      token:
        # Auth Server clock can be xx seconds ahead of resource server
        lifespan-grace: 120
      roles:
        role-claim-path: "realm_access/roles"

    oidc-client:
      client-id: provoly
      credentials:
        secret: secret
      grant:
        type: password
      auth-server-url: http://localhost:9080/realms/provoly

    rest-client:
      "data-virt":
        url: http://localhost:8080
      "data-ref":
        url: http://localhost:8180

    otel:
      enabled: false

    log:
      category:
        "io.quarkus":
          level: INFO
        "com.provoly":
          level: DEBUG
        "org.apache.kafka":
          level: DEBUG

    http:
      port: 8280

  kafka:
    bootstrap:
      servers: localhost:9093

  provoly:
    sync:
      user: provoly_sync
      password: password
    application:
      version: dev
      chart:
        version: dev

"%prod":
  quarkus:
    kubernetes-config:
      enabled: true
      config-maps: data-sync
      secrets:
        enabled: true
        ~: data-sync