version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0@sha256:93a9a7e1908f0c59ffce42ff494791bd785c36de40189759fc2a0ed7d6006c9d
    container_name: es01
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ${PWD}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - provoly
#
#  kib01:
#    image: docker.elastic.co/kibana/kibana:8.4.1
#    container_name: kib01
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://es01:9200
#    networks:
#      - provoly

  db01:
    image: postgres:17.0-alpine@sha256:d388be15cfb665c723da47cccdc7ea5c003ed71f700c5419bbd075033227ce1f
    container_name: db01
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - POSTGRES_DB=default
    networks:
      - provoly

  ref01:
    image: quarkus/data-ref-jvm-dirty
    container_name: ref01
    ports:
      - "8180:8180"
    networks:
      - provoly

volumes:
  data-es-01:
    driver: local

networks:
  provoly: