version: '2.2'
services:
  #
  #  kib01:
  #    image: docker.elastic.co/kibana/kibana:8.4.1
  #    container_name: kib01
  #    ports:
  #      - "5601:5601"
  #    environment:
  #      - ELASTICSEARCH_HOSTS=http://es01:9200
  #    networks:
  #      - provoly

  db01:
    image: postgres:17.1-alpine@sha256:0d9624535618a135c5453258fd629f4963390338b11aaffb92292c12df3a6c17
    container_name: db01
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - POSTGRES_DB=default
    networks:
      - provoly

  ref01:
    image: quarkus/data-ref-jvm-dirty
    container_name: ref01
    ports:
      - "8180:8180"
    networks:
      - provoly

volumes:
  data-es-01:
    driver: local

networks:
  provoly: