name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

env:
  JAVA_VERSION: 21
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.showDateTime=true -Djansi.force=true"
  MAVEN_CLI_OPTS: "-Dstyle.color=always --batch-mode --errors --show-version -DinstallAtEnd=true -Dno-format -DdeployAtEnd=true"
  SKIP_TEST: "false"
  MAVEN_JIB_OPTIONS:  "-Dquarkus.container-image.labels.\"git-ref\"=${{ github.sha }} -Djib.serialize=true"
  IMAGE_NAME: "-Dquarkus.container-image.tag=latest"

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre_job:
    name: Preparing path-ignores
    runs-on: provoly-runner
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '[".gitignore","LICENSE","*.adoc","*.txt","docs/**", "ide-config", ".github/**"]'
          do_not_skip: '["workflow_dispatch"]'
          skip_after_successful_duplicate: false
  build:
    name: Build
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: provoly-runner
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      #PREPARE RUNNER
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.1
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # VALIDATE SOURCE FORMAT
      - name: Validate source format
        id: spotless
        run: mvn $MAVEN_CLI_OPTS -Dvalidate compile

      # RUN OPENAPI SPECIFICATIONS LINTER
      - name: Validate openapi specification files
        id: redocly-lint
        run: npx @redocly/cli lint --format github-actions

      - name: Prepare Short Sha
        id: shortSha
        run: | 
          export "CI_SHORT_COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-8)"
          echo "CI_SHORT_COMMIT_SHA=$CI_SHORT_COMMIT_SHA" >> $GITHUB_ENV

      # CHECK AND BUILD REF IF NEEDED
      - name: Check Ref modification
        id: changed-ref-files
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            data-ref/**
            provoly-common/**/*
            provoly-common-test/**/*
            provoly-parent/**/*
            provoly-parent-build-quarkus/**/*

      # RUN SCRIPT TO GET TARGETED PROJECTS
      # FOR MAIN ONLY, push image on repository
      - name: Sets env vars for main branch
        id: main-branch
        run: |
          echo "DOCKER_IMAGE_ADDITIONAL_TAGS=dev-$CI_SHORT_COMMIT_SHA" >> $GITHUB_ENV
          echo "SKIP_TEST=true" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - name: Build Ref
        id: ref-build
        run: mvn ${{ env.MAVEN_CLI_OPTS }} -DskipTests=${{ env.SKIP_TEST }} verify -pl data-ref -Dquarkus.container-image.additional-tags=${{ env.DOCKER_IMAGE_ADDITIONAL_TAGS }} -am  ${{ env.MAVEN_JIB_OPTIONS }} ${{ env.IMAGE_NAME }} -Pdocker-image
        if: steps.changed-ref-files.outputs.any_changed == 'true'
        env:
          CI_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          CI_REGISTRY_SERVER: ${{ vars.REGISTRY_URL }}
          CI_REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          CI_REGISTRY_PROJECT_NAME: provoly

      #  CHECK AND BUILD REQUIRED MODULES
      - name: Detect Changes
        uses: jbangdev/jbang-action@v0.115.0
        with:
          script: ./ci/scripts/CiScripts.java
          scriptargs: select-target-modules --merge_request=${{ github.event.pull_request.base.sha }}
            --mr-diff-base-sha=${{ github.event.pull_request.base.sha }}
            --mr-source-branch-name=${{ github.head_ref }}
            --mr-target-branch-name=${{ github.base_ref }}
            --commit-sha=${{ github.sha }}

      - name: Output changes
        run: echo "$(cat build.env)" >> $GITHUB_ENV

      - name: Build Modules
        id: modules-build
        run: mvn ${{ env.MAVEN_CLI_OPTS }} -DskipTests=${{ env.SKIP_TEST }} verify -pl ${{ env.MODULES }} -am ${{ env.MAVEN_JIB_OPTIONS }} ${{ env.IMAGE_NAME }} -Dquarkus.container-image.additional-tags=${{env.DOCKER_IMAGE_ADDITIONAL_TAGS}} -Pdocker-image
        env:
          CI_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          CI_REGISTRY_SERVER: ${{ vars.REGISTRY_URL }}
          CI_REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          CI_REGISTRY_PROJECT_NAME: provoly

      - name: Summary
        if: always()
        run: |
          echo "# Steps status " >> $GITHUB_STEP_SUMMARY
          echo "| Step | State |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Setting up runner | ${{ steps.cache-maven.outcome }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Running for main | ${{ github.ref == 'refs/heads/main' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Spotless | ${{ steps.spotless.outcome }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build data-ref | ${{ steps.id.ref-build.outcome }} |" >> $GITHUB_STEP_SUMMARY
          echo "| changed modules |  ${{ env.MODULES }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build modules | ${{ steps.modules-build.outcome }} |" >> $GITHUB_STEP_SUMMARY
